# Generated by Django 6.1.1 on 2026-09-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('message', models.TextField(verbose_name='متن نظر')),
                ('rating', models.IntegerField(choices=[(5, '★★★★★ عالی'), (4, '★★★★ خوب'), (3, '★★★ متوسط'), (2, '★★ ضعیف'), (1, '★ خیلی ضعیف')], default=5, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
        ),
    ]
